name: Docs
on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:
concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: 'nightly'
      - name: Set CAT packages to develop & resolve env
        run: |
          julia --project=docs/ -e 'using Pkg;
                                    Pkg.instantiate()'
      - uses: julia-actions/julia-buildpkg@v1
        with:
          project: 'docs'
      - name: Install GitHubActions.jl in docs env
        run: |
          julia --project=docs/ -e '
            using Pkg;
            Pkg.add(Pkg.PackageSpec(name="GitHubActions", version="0.1"))'
      - name: Install dependencies
        run: julia --project=docs/ -e '
            using Pkg;
            Pkg.develop(PackageSpec(path=pwd()));
            Pkg.instantiate()'
      - name: Make docs
        run: |
          julia --project=docs/ -e '
            include("docs/make.jl")'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
